name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@036d1f15bd6f56e35e75a8da1e2ef85e0bd0e3ba # v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        fingerprint: ${{ secrets.EC2_HOST_FINGERPRINT }}
        script: |
          cd /var/www/ohmai.me
          git fetch origin main
          git reset --hard origin/main
          echo "Deploy completed at $(date)"
